# Generated by Django 5.1.6 on 2025-03-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('room_number', models.CharField(max_length=10)),
                ('check_in_date', models.DateField()),
                ('fee_status', models.BooleanField(default=False)),
            ],
        ),
    ]
