# Generated by Django 5.1.6 on 2025-03-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_education_achievements_education_gpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='github',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='website',
        ),
        migrations.AddField(
            model_name='education',
            name='current_education',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='education_level',
            field=models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'Ph.D.'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
