# Generated by Django 5.1.6 on 2025-03-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_remove_user_from_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='linkedin',
            field=models.TextField(blank=True),
        ),
    ]
